import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../settings/colors.css";
import "../settings/typography.css";
import "./globals.css";
import { roboto } from "./font";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.variable}>{children}</body>
    </html>
  );
}
